/**
 *
 *  ArticleMdImage.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ArticleMdImage.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::win_xp_db;

const std::string ArticleMdImage::Cols::_id = "id";
const std::string ArticleMdImage::Cols::_article_id = "article_id";
const std::string ArticleMdImage::Cols::_image_name = "image_name";
const std::string ArticleMdImage::Cols::_mime_type = "mime_type";
const std::string ArticleMdImage::Cols::_image_data = "image_data";
const std::string ArticleMdImage::Cols::_created_at = "created_at";
const std::string ArticleMdImage::primaryKeyName = "id";
const bool ArticleMdImage::hasPrimaryKey = true;
const std::string ArticleMdImage::tableName = "article_md_image";

const std::vector<typename ArticleMdImage::MetaData> ArticleMdImage::metaData_={
{"id","int64_t","bigint(20)",8,1,1,1},
{"article_id","int64_t","bigint(20)",8,0,0,1},
{"image_name","std::string","varchar(255)",255,0,0,1},
{"mime_type","std::string","varchar(100)",100,0,0,1},
{"image_data","std::vector<char>","longblob",0,0,0,1},
{"created_at","::trantor::Date","datetime",0,0,0,1}
};
const std::string &ArticleMdImage::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ArticleMdImage::ArticleMdImage(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["article_id"].isNull())
        {
            articleId_=std::make_shared<int64_t>(r["article_id"].as<int64_t>());
        }
        if(!r["image_name"].isNull())
        {
            imageName_=std::make_shared<std::string>(r["image_name"].as<std::string>());
        }
        if(!r["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(r["mime_type"].as<std::string>());
        }
        if(!r["image_data"].isNull())
        {
            imageData_=std::make_shared<std::vector<char>>(r["image_data"].as<std::vector<char>>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            articleId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            imageName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            mimeType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            imageData_=std::make_shared<std::vector<char>>(r[index].as<std::vector<char>>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

ArticleMdImage::ArticleMdImage(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            articleId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            imageName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto str = pJson[pMasqueradingVector[4]].asString();
            imageData_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

ArticleMdImage::ArticleMdImage(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("article_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["article_id"].isNull())
        {
            articleId_=std::make_shared<int64_t>((int64_t)pJson["article_id"].asInt64());
        }
    }
    if(pJson.isMember("image_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["image_name"].isNull())
        {
            imageName_=std::make_shared<std::string>(pJson["image_name"].asString());
        }
    }
    if(pJson.isMember("mime_type"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson["mime_type"].asString());
        }
    }
    if(pJson.isMember("image_data"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["image_data"].isNull())
        {
            auto str = pJson["image_data"].asString();
            imageData_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ArticleMdImage::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            articleId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            imageName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto str = pJson[pMasqueradingVector[4]].asString();
            imageData_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ArticleMdImage::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("article_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["article_id"].isNull())
        {
            articleId_=std::make_shared<int64_t>((int64_t)pJson["article_id"].asInt64());
        }
    }
    if(pJson.isMember("image_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["image_name"].isNull())
        {
            imageName_=std::make_shared<std::string>(pJson["image_name"].asString());
        }
    }
    if(pJson.isMember("mime_type"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["mime_type"].isNull())
        {
            mimeType_=std::make_shared<std::string>(pJson["mime_type"].asString());
        }
    }
    if(pJson.isMember("image_data"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["image_data"].isNull())
        {
            auto str = pJson["image_data"].asString();
            imageData_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &ArticleMdImage::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ArticleMdImage::getId() const noexcept
{
    return id_;
}
void ArticleMdImage::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ArticleMdImage::PrimaryKeyType & ArticleMdImage::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &ArticleMdImage::getValueOfArticleId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(articleId_)
        return *articleId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ArticleMdImage::getArticleId() const noexcept
{
    return articleId_;
}
void ArticleMdImage::setArticleId(const int64_t &pArticleId) noexcept
{
    articleId_ = std::make_shared<int64_t>(pArticleId);
    dirtyFlag_[1] = true;
}

const std::string &ArticleMdImage::getValueOfImageName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imageName_)
        return *imageName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ArticleMdImage::getImageName() const noexcept
{
    return imageName_;
}
void ArticleMdImage::setImageName(const std::string &pImageName) noexcept
{
    imageName_ = std::make_shared<std::string>(pImageName);
    dirtyFlag_[2] = true;
}
void ArticleMdImage::setImageName(std::string &&pImageName) noexcept
{
    imageName_ = std::make_shared<std::string>(std::move(pImageName));
    dirtyFlag_[2] = true;
}

const std::string &ArticleMdImage::getValueOfMimeType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mimeType_)
        return *mimeType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ArticleMdImage::getMimeType() const noexcept
{
    return mimeType_;
}
void ArticleMdImage::setMimeType(const std::string &pMimeType) noexcept
{
    mimeType_ = std::make_shared<std::string>(pMimeType);
    dirtyFlag_[3] = true;
}
void ArticleMdImage::setMimeType(std::string &&pMimeType) noexcept
{
    mimeType_ = std::make_shared<std::string>(std::move(pMimeType));
    dirtyFlag_[3] = true;
}

const std::vector<char> &ArticleMdImage::getValueOfImageData() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(imageData_)
        return *imageData_;
    return defaultValue;
}
std::string ArticleMdImage::getValueOfImageDataAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imageData_)
        return std::string(imageData_->data(),imageData_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &ArticleMdImage::getImageData() const noexcept
{
    return imageData_;
}
void ArticleMdImage::setImageData(const std::vector<char> &pImageData) noexcept
{
    imageData_ = std::make_shared<std::vector<char>>(pImageData);
    dirtyFlag_[4] = true;
}
void ArticleMdImage::setImageData(const std::string &pImageData) noexcept
{
    imageData_ = std::make_shared<std::vector<char>>(pImageData.c_str(),pImageData.c_str()+pImageData.length());
    dirtyFlag_[4] = true;
}

const ::trantor::Date &ArticleMdImage::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ArticleMdImage::getCreatedAt() const noexcept
{
    return createdAt_;
}
void ArticleMdImage::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[5] = true;
}

void ArticleMdImage::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &ArticleMdImage::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "article_id",
        "image_name",
        "mime_type",
        "image_data",
        "created_at"
    };
    return inCols;
}

void ArticleMdImage::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getArticleId())
        {
            binder << getValueOfArticleId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getImageName())
        {
            binder << getValueOfImageName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMimeType())
        {
            binder << getValueOfMimeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getImageData())
        {
            binder << getValueOfImageData();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ArticleMdImage::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void ArticleMdImage::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getArticleId())
        {
            binder << getValueOfArticleId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getImageName())
        {
            binder << getValueOfImageName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMimeType())
        {
            binder << getValueOfMimeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getImageData())
        {
            binder << getValueOfImageData();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ArticleMdImage::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getArticleId())
    {
        ret["article_id"]=(Json::Int64)getValueOfArticleId();
    }
    else
    {
        ret["article_id"]=Json::Value();
    }
    if(getImageName())
    {
        ret["image_name"]=getValueOfImageName();
    }
    else
    {
        ret["image_name"]=Json::Value();
    }
    if(getMimeType())
    {
        ret["mime_type"]=getValueOfMimeType();
    }
    else
    {
        ret["mime_type"]=Json::Value();
    }
    if(getImageData())
    {
        ret["image_data"]=drogon::utils::base64Encode((const unsigned char *)getImageData()->data(),getImageData()->size());
    }
    else
    {
        ret["image_data"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string ArticleMdImage::toString() const
{
    return toJson().toStyledString();
}

Json::Value ArticleMdImage::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getArticleId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfArticleId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getImageName())
            {
                ret[pMasqueradingVector[2]]=getValueOfImageName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMimeType())
            {
                ret[pMasqueradingVector[3]]=getValueOfMimeType();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getImageData())
            {
                ret[pMasqueradingVector[4]]=drogon::utils::base64Encode((const unsigned char *)getImageData()->data(),getImageData()->size());
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[5]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getArticleId())
    {
        ret["article_id"]=(Json::Int64)getValueOfArticleId();
    }
    else
    {
        ret["article_id"]=Json::Value();
    }
    if(getImageName())
    {
        ret["image_name"]=getValueOfImageName();
    }
    else
    {
        ret["image_name"]=Json::Value();
    }
    if(getMimeType())
    {
        ret["mime_type"]=getValueOfMimeType();
    }
    else
    {
        ret["mime_type"]=Json::Value();
    }
    if(getImageData())
    {
        ret["image_data"]=drogon::utils::base64Encode((const unsigned char *)getImageData()->data(),getImageData()->size());
    }
    else
    {
        ret["image_data"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool ArticleMdImage::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("article_id"))
    {
        if(!validJsonOfField(1, "article_id", pJson["article_id"], err, true))
            return false;
    }
    else
    {
        err="The article_id column cannot be null";
        return false;
    }
    if(pJson.isMember("image_name"))
    {
        if(!validJsonOfField(2, "image_name", pJson["image_name"], err, true))
            return false;
    }
    else
    {
        err="The image_name column cannot be null";
        return false;
    }
    if(pJson.isMember("mime_type"))
    {
        if(!validJsonOfField(3, "mime_type", pJson["mime_type"], err, true))
            return false;
    }
    else
    {
        err="The mime_type column cannot be null";
        return false;
    }
    if(pJson.isMember("image_data"))
    {
        if(!validJsonOfField(4, "image_data", pJson["image_data"], err, true))
            return false;
    }
    else
    {
        err="The image_data column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(5, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool ArticleMdImage::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ArticleMdImage::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("article_id"))
    {
        if(!validJsonOfField(1, "article_id", pJson["article_id"], err, false))
            return false;
    }
    if(pJson.isMember("image_name"))
    {
        if(!validJsonOfField(2, "image_name", pJson["image_name"], err, false))
            return false;
    }
    if(pJson.isMember("mime_type"))
    {
        if(!validJsonOfField(3, "mime_type", pJson["mime_type"], err, false))
            return false;
    }
    if(pJson.isMember("image_data"))
    {
        if(!validJsonOfField(4, "image_data", pJson["image_data"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(5, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool ArticleMdImage::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ArticleMdImage::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
