/**
 *
 *  DesktopIcon.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "DesktopIcon.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::win_xp_db;

const std::string DesktopIcon::Cols::_desktop_id = "desktop_id";
const std::string DesktopIcon::Cols::_desktop_name = "desktop_name";
const std::string DesktopIcon::Cols::_desktop_image = "desktop_image";
const std::string DesktopIcon::Cols::_desktop_url = "desktop_url";
const std::string DesktopIcon::primaryKeyName = "desktop_id";
const bool DesktopIcon::hasPrimaryKey = true;
const std::string DesktopIcon::tableName = "desktop_icon";

const std::vector<typename DesktopIcon::MetaData> DesktopIcon::metaData_={
{"desktop_id","int32_t","int(11)",4,1,1,1},
{"desktop_name","std::string","varchar(64)",64,0,0,1},
{"desktop_image","std::string","mediumtext",0,0,0,0},
{"desktop_url","std::string","varchar(64)",64,0,0,1}
};
const std::string &DesktopIcon::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
DesktopIcon::DesktopIcon(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["desktop_id"].isNull())
        {
            desktopId_=std::make_shared<int32_t>(r["desktop_id"].as<int32_t>());
        }
        if(!r["desktop_name"].isNull())
        {
            desktopName_=std::make_shared<std::string>(r["desktop_name"].as<std::string>());
        }
        if(!r["desktop_image"].isNull())
        {
            desktopImage_=std::make_shared<std::string>(r["desktop_image"].as<std::string>());
        }
        if(!r["desktop_url"].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(r["desktop_url"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            desktopId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            desktopName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            desktopImage_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

DesktopIcon::DesktopIcon(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            desktopId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            desktopName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            desktopImage_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

DesktopIcon::DesktopIcon(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("desktop_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["desktop_id"].isNull())
        {
            desktopId_=std::make_shared<int32_t>((int32_t)pJson["desktop_id"].asInt64());
        }
    }
    if(pJson.isMember("desktop_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["desktop_name"].isNull())
        {
            desktopName_=std::make_shared<std::string>(pJson["desktop_name"].asString());
        }
    }
    if(pJson.isMember("desktop_image"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["desktop_image"].isNull())
        {
            desktopImage_=std::make_shared<std::string>(pJson["desktop_image"].asString());
        }
    }
    if(pJson.isMember("desktop_url"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["desktop_url"].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(pJson["desktop_url"].asString());
        }
    }
}

void DesktopIcon::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            desktopId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            desktopName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            desktopImage_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void DesktopIcon::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("desktop_id"))
    {
        if(!pJson["desktop_id"].isNull())
        {
            desktopId_=std::make_shared<int32_t>((int32_t)pJson["desktop_id"].asInt64());
        }
    }
    if(pJson.isMember("desktop_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["desktop_name"].isNull())
        {
            desktopName_=std::make_shared<std::string>(pJson["desktop_name"].asString());
        }
    }
    if(pJson.isMember("desktop_image"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["desktop_image"].isNull())
        {
            desktopImage_=std::make_shared<std::string>(pJson["desktop_image"].asString());
        }
    }
    if(pJson.isMember("desktop_url"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["desktop_url"].isNull())
        {
            desktopUrl_=std::make_shared<std::string>(pJson["desktop_url"].asString());
        }
    }
}

const int32_t &DesktopIcon::getValueOfDesktopId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(desktopId_)
        return *desktopId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &DesktopIcon::getDesktopId() const noexcept
{
    return desktopId_;
}
void DesktopIcon::setDesktopId(const int32_t &pDesktopId) noexcept
{
    desktopId_ = std::make_shared<int32_t>(pDesktopId);
    dirtyFlag_[0] = true;
}
const typename DesktopIcon::PrimaryKeyType & DesktopIcon::getPrimaryKey() const
{
    assert(desktopId_);
    return *desktopId_;
}

const std::string &DesktopIcon::getValueOfDesktopName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(desktopName_)
        return *desktopName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DesktopIcon::getDesktopName() const noexcept
{
    return desktopName_;
}
void DesktopIcon::setDesktopName(const std::string &pDesktopName) noexcept
{
    desktopName_ = std::make_shared<std::string>(pDesktopName);
    dirtyFlag_[1] = true;
}
void DesktopIcon::setDesktopName(std::string &&pDesktopName) noexcept
{
    desktopName_ = std::make_shared<std::string>(std::move(pDesktopName));
    dirtyFlag_[1] = true;
}

const std::string &DesktopIcon::getValueOfDesktopImage() const noexcept
{
    static const std::string defaultValue = std::string();
    if(desktopImage_)
        return *desktopImage_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DesktopIcon::getDesktopImage() const noexcept
{
    return desktopImage_;
}
void DesktopIcon::setDesktopImage(const std::string &pDesktopImage) noexcept
{
    desktopImage_ = std::make_shared<std::string>(pDesktopImage);
    dirtyFlag_[2] = true;
}
void DesktopIcon::setDesktopImage(std::string &&pDesktopImage) noexcept
{
    desktopImage_ = std::make_shared<std::string>(std::move(pDesktopImage));
    dirtyFlag_[2] = true;
}
void DesktopIcon::setDesktopImageToNull() noexcept
{
    desktopImage_.reset();
    dirtyFlag_[2] = true;
}

const std::string &DesktopIcon::getValueOfDesktopUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(desktopUrl_)
        return *desktopUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DesktopIcon::getDesktopUrl() const noexcept
{
    return desktopUrl_;
}
void DesktopIcon::setDesktopUrl(const std::string &pDesktopUrl) noexcept
{
    desktopUrl_ = std::make_shared<std::string>(pDesktopUrl);
    dirtyFlag_[3] = true;
}
void DesktopIcon::setDesktopUrl(std::string &&pDesktopUrl) noexcept
{
    desktopUrl_ = std::make_shared<std::string>(std::move(pDesktopUrl));
    dirtyFlag_[3] = true;
}

void DesktopIcon::updateId(const uint64_t id)
{
    desktopId_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &DesktopIcon::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "desktop_name",
        "desktop_image",
        "desktop_url"
    };
    return inCols;
}

void DesktopIcon::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDesktopName())
        {
            binder << getValueOfDesktopName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDesktopImage())
        {
            binder << getValueOfDesktopImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDesktopUrl())
        {
            binder << getValueOfDesktopUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> DesktopIcon::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void DesktopIcon::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDesktopName())
        {
            binder << getValueOfDesktopName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDesktopImage())
        {
            binder << getValueOfDesktopImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDesktopUrl())
        {
            binder << getValueOfDesktopUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value DesktopIcon::toJson() const
{
    Json::Value ret;
    if(getDesktopId())
    {
        ret["desktop_id"]=getValueOfDesktopId();
    }
    else
    {
        ret["desktop_id"]=Json::Value();
    }
    if(getDesktopName())
    {
        ret["desktop_name"]=getValueOfDesktopName();
    }
    else
    {
        ret["desktop_name"]=Json::Value();
    }
    if(getDesktopImage())
    {
        ret["desktop_image"]=getValueOfDesktopImage();
    }
    else
    {
        ret["desktop_image"]=Json::Value();
    }
    if(getDesktopUrl())
    {
        ret["desktop_url"]=getValueOfDesktopUrl();
    }
    else
    {
        ret["desktop_url"]=Json::Value();
    }
    return ret;
}

std::string DesktopIcon::toString() const
{
    return toJson().toStyledString();
}

Json::Value DesktopIcon::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getDesktopId())
            {
                ret[pMasqueradingVector[0]]=getValueOfDesktopId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDesktopName())
            {
                ret[pMasqueradingVector[1]]=getValueOfDesktopName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDesktopImage())
            {
                ret[pMasqueradingVector[2]]=getValueOfDesktopImage();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDesktopUrl())
            {
                ret[pMasqueradingVector[3]]=getValueOfDesktopUrl();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getDesktopId())
    {
        ret["desktop_id"]=getValueOfDesktopId();
    }
    else
    {
        ret["desktop_id"]=Json::Value();
    }
    if(getDesktopName())
    {
        ret["desktop_name"]=getValueOfDesktopName();
    }
    else
    {
        ret["desktop_name"]=Json::Value();
    }
    if(getDesktopImage())
    {
        ret["desktop_image"]=getValueOfDesktopImage();
    }
    else
    {
        ret["desktop_image"]=Json::Value();
    }
    if(getDesktopUrl())
    {
        ret["desktop_url"]=getValueOfDesktopUrl();
    }
    else
    {
        ret["desktop_url"]=Json::Value();
    }
    return ret;
}

bool DesktopIcon::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("desktop_id"))
    {
        if(!validJsonOfField(0, "desktop_id", pJson["desktop_id"], err, true))
            return false;
    }
    if(pJson.isMember("desktop_name"))
    {
        if(!validJsonOfField(1, "desktop_name", pJson["desktop_name"], err, true))
            return false;
    }
    else
    {
        err="The desktop_name column cannot be null";
        return false;
    }
    if(pJson.isMember("desktop_image"))
    {
        if(!validJsonOfField(2, "desktop_image", pJson["desktop_image"], err, true))
            return false;
    }
    if(pJson.isMember("desktop_url"))
    {
        if(!validJsonOfField(3, "desktop_url", pJson["desktop_url"], err, true))
            return false;
    }
    else
    {
        err="The desktop_url column cannot be null";
        return false;
    }
    return true;
}
bool DesktopIcon::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DesktopIcon::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("desktop_id"))
    {
        if(!validJsonOfField(0, "desktop_id", pJson["desktop_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("desktop_name"))
    {
        if(!validJsonOfField(1, "desktop_name", pJson["desktop_name"], err, false))
            return false;
    }
    if(pJson.isMember("desktop_image"))
    {
        if(!validJsonOfField(2, "desktop_image", pJson["desktop_image"], err, false))
            return false;
    }
    if(pJson.isMember("desktop_url"))
    {
        if(!validJsonOfField(3, "desktop_url", pJson["desktop_url"], err, false))
            return false;
    }
    return true;
}
bool DesktopIcon::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DesktopIcon::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
