/**
 *
 *  FileResource.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace win_xp_db
{

class FileResource
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _category_id;
        static const std::string _file_name;
        static const std::string _file_ext;
        static const std::string _relative_path;
        static const std::string _absolute_path;
        static const std::string _file_size;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit FileResource(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit FileResource(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    FileResource(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    FileResource() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column category_id  */
    ///Get the value of the column category_id, returns the default value if the column is null
    const int64_t &getValueOfCategoryId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getCategoryId() const noexcept;
    ///Set the value of the column category_id
    void setCategoryId(const int64_t &pCategoryId) noexcept;

    /**  For column file_name  */
    ///Get the value of the column file_name, returns the default value if the column is null
    const std::string &getValueOfFileName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFileName() const noexcept;
    ///Set the value of the column file_name
    void setFileName(const std::string &pFileName) noexcept;
    void setFileName(std::string &&pFileName) noexcept;

    /**  For column file_ext  */
    ///Get the value of the column file_ext, returns the default value if the column is null
    const std::string &getValueOfFileExt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFileExt() const noexcept;
    ///Set the value of the column file_ext
    void setFileExt(const std::string &pFileExt) noexcept;
    void setFileExt(std::string &&pFileExt) noexcept;
    void setFileExtToNull() noexcept;

    /**  For column relative_path  */
    ///Get the value of the column relative_path, returns the default value if the column is null
    const std::string &getValueOfRelativePath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRelativePath() const noexcept;
    ///Set the value of the column relative_path
    void setRelativePath(const std::string &pRelativePath) noexcept;
    void setRelativePath(std::string &&pRelativePath) noexcept;

    /**  For column absolute_path  */
    ///Get the value of the column absolute_path, returns the default value if the column is null
    const std::string &getValueOfAbsolutePath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAbsolutePath() const noexcept;
    ///Set the value of the column absolute_path
    void setAbsolutePath(const std::string &pAbsolutePath) noexcept;
    void setAbsolutePath(std::string &&pAbsolutePath) noexcept;
    void setAbsolutePathToNull() noexcept;

    /**  For column file_size  */
    ///Get the value of the column file_size, returns the default value if the column is null
    const int64_t &getValueOfFileSize() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getFileSize() const noexcept;
    ///Set the value of the column file_size
    void setFileSize(const int64_t &pFileSize) noexcept;
    void setFileSizeToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<FileResource>;
    friend drogon::orm::BaseBuilder<FileResource, true, true>;
    friend drogon::orm::BaseBuilder<FileResource, true, false>;
    friend drogon::orm::BaseBuilder<FileResource, false, true>;
    friend drogon::orm::BaseBuilder<FileResource, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<FileResource>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> categoryId_;
    std::shared_ptr<std::string> fileName_;
    std::shared_ptr<std::string> fileExt_;
    std::shared_ptr<std::string> relativePath_;
    std::shared_ptr<std::string> absolutePath_;
    std::shared_ptr<int64_t> fileSize_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "category_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "file_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "file_ext,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "relative_path,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "absolute_path,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "file_size,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "created_at,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace win_xp_db
} // namespace drogon_model
