/**
 *
 *  WinUser.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "WinUser.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::win_xp_db;

const std::string WinUser::Cols::_user_id = "user_id";
const std::string WinUser::Cols::_user_icon = "user_icon";
const std::string WinUser::Cols::_user_name = "user_name";
const std::string WinUser::Cols::_user_email = "user_email";
const std::string WinUser::Cols::_user_password = "user_password";
const std::string WinUser::Cols::_user_entry_date = "user_entry_date";
const std::string WinUser::primaryKeyName = "user_id";
const bool WinUser::hasPrimaryKey = true;
const std::string WinUser::tableName = "win_user";

const std::vector<typename WinUser::MetaData> WinUser::metaData_={
{"user_id","int32_t","int(11)",4,1,1,1},
{"user_icon","std::string","varchar(128)",128,0,0,0},
{"user_name","std::string","varchar(32)",32,0,0,1},
{"user_email","std::string","varchar(128)",128,0,0,1},
{"user_password","std::string","varchar(64)",64,0,0,1},
{"user_entry_date","::trantor::Date","datetime",0,0,0,1}
};
const std::string &WinUser::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
WinUser::WinUser(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["user_icon"].isNull())
        {
            userIcon_=std::make_shared<std::string>(r["user_icon"].as<std::string>());
        }
        if(!r["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(r["user_name"].as<std::string>());
        }
        if(!r["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(r["user_email"].as<std::string>());
        }
        if(!r["user_password"].isNull())
        {
            userPassword_=std::make_shared<std::string>(r["user_password"].as<std::string>());
        }
        if(!r["user_entry_date"].isNull())
        {
            auto timeStr = r["user_entry_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userIcon_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            userEmail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            userPassword_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

WinUser::WinUser(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userIcon_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userPassword_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

WinUser::WinUser(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("user_icon"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_icon"].isNull())
        {
            userIcon_=std::make_shared<std::string>(pJson["user_icon"].asString());
        }
    }
    if(pJson.isMember("user_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(pJson["user_name"].asString());
        }
    }
    if(pJson.isMember("user_email"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson["user_email"].asString());
        }
    }
    if(pJson.isMember("user_password"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["user_password"].isNull())
        {
            userPassword_=std::make_shared<std::string>(pJson["user_password"].asString());
        }
    }
    if(pJson.isMember("user_entry_date"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["user_entry_date"].isNull())
        {
            auto timeStr = pJson["user_entry_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WinUser::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userIcon_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userPassword_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WinUser::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("user_icon"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_icon"].isNull())
        {
            userIcon_=std::make_shared<std::string>(pJson["user_icon"].asString());
        }
    }
    if(pJson.isMember("user_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_name"].isNull())
        {
            userName_=std::make_shared<std::string>(pJson["user_name"].asString());
        }
    }
    if(pJson.isMember("user_email"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["user_email"].isNull())
        {
            userEmail_=std::make_shared<std::string>(pJson["user_email"].asString());
        }
    }
    if(pJson.isMember("user_password"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["user_password"].isNull())
        {
            userPassword_=std::make_shared<std::string>(pJson["user_password"].asString());
        }
    }
    if(pJson.isMember("user_entry_date"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["user_entry_date"].isNull())
        {
            auto timeStr = pJson["user_entry_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                userEntryDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &WinUser::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WinUser::getUserId() const noexcept
{
    return userId_;
}
void WinUser::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[0] = true;
}
const typename WinUser::PrimaryKeyType & WinUser::getPrimaryKey() const
{
    assert(userId_);
    return *userId_;
}

const std::string &WinUser::getValueOfUserIcon() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userIcon_)
        return *userIcon_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WinUser::getUserIcon() const noexcept
{
    return userIcon_;
}
void WinUser::setUserIcon(const std::string &pUserIcon) noexcept
{
    userIcon_ = std::make_shared<std::string>(pUserIcon);
    dirtyFlag_[1] = true;
}
void WinUser::setUserIcon(std::string &&pUserIcon) noexcept
{
    userIcon_ = std::make_shared<std::string>(std::move(pUserIcon));
    dirtyFlag_[1] = true;
}
void WinUser::setUserIconToNull() noexcept
{
    userIcon_.reset();
    dirtyFlag_[1] = true;
}

const std::string &WinUser::getValueOfUserName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userName_)
        return *userName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WinUser::getUserName() const noexcept
{
    return userName_;
}
void WinUser::setUserName(const std::string &pUserName) noexcept
{
    userName_ = std::make_shared<std::string>(pUserName);
    dirtyFlag_[2] = true;
}
void WinUser::setUserName(std::string &&pUserName) noexcept
{
    userName_ = std::make_shared<std::string>(std::move(pUserName));
    dirtyFlag_[2] = true;
}

const std::string &WinUser::getValueOfUserEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userEmail_)
        return *userEmail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WinUser::getUserEmail() const noexcept
{
    return userEmail_;
}
void WinUser::setUserEmail(const std::string &pUserEmail) noexcept
{
    userEmail_ = std::make_shared<std::string>(pUserEmail);
    dirtyFlag_[3] = true;
}
void WinUser::setUserEmail(std::string &&pUserEmail) noexcept
{
    userEmail_ = std::make_shared<std::string>(std::move(pUserEmail));
    dirtyFlag_[3] = true;
}

const std::string &WinUser::getValueOfUserPassword() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userPassword_)
        return *userPassword_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WinUser::getUserPassword() const noexcept
{
    return userPassword_;
}
void WinUser::setUserPassword(const std::string &pUserPassword) noexcept
{
    userPassword_ = std::make_shared<std::string>(pUserPassword);
    dirtyFlag_[4] = true;
}
void WinUser::setUserPassword(std::string &&pUserPassword) noexcept
{
    userPassword_ = std::make_shared<std::string>(std::move(pUserPassword));
    dirtyFlag_[4] = true;
}

const ::trantor::Date &WinUser::getValueOfUserEntryDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(userEntryDate_)
        return *userEntryDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WinUser::getUserEntryDate() const noexcept
{
    return userEntryDate_;
}
void WinUser::setUserEntryDate(const ::trantor::Date &pUserEntryDate) noexcept
{
    userEntryDate_ = std::make_shared<::trantor::Date>(pUserEntryDate);
    dirtyFlag_[5] = true;
}

void WinUser::updateId(const uint64_t id)
{
    userId_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &WinUser::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_icon",
        "user_name",
        "user_email",
        "user_password",
        "user_entry_date"
    };
    return inCols;
}

void WinUser::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserIcon())
        {
            binder << getValueOfUserIcon();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserName())
        {
            binder << getValueOfUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserEmail())
        {
            binder << getValueOfUserEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserPassword())
        {
            binder << getValueOfUserPassword();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserEntryDate())
        {
            binder << getValueOfUserEntryDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> WinUser::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void WinUser::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserIcon())
        {
            binder << getValueOfUserIcon();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserName())
        {
            binder << getValueOfUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserEmail())
        {
            binder << getValueOfUserEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserPassword())
        {
            binder << getValueOfUserPassword();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserEntryDate())
        {
            binder << getValueOfUserEntryDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value WinUser::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserIcon())
    {
        ret["user_icon"]=getValueOfUserIcon();
    }
    else
    {
        ret["user_icon"]=Json::Value();
    }
    if(getUserName())
    {
        ret["user_name"]=getValueOfUserName();
    }
    else
    {
        ret["user_name"]=Json::Value();
    }
    if(getUserEmail())
    {
        ret["user_email"]=getValueOfUserEmail();
    }
    else
    {
        ret["user_email"]=Json::Value();
    }
    if(getUserPassword())
    {
        ret["user_password"]=getValueOfUserPassword();
    }
    else
    {
        ret["user_password"]=Json::Value();
    }
    if(getUserEntryDate())
    {
        ret["user_entry_date"]=getUserEntryDate()->toDbStringLocal();
    }
    else
    {
        ret["user_entry_date"]=Json::Value();
    }
    return ret;
}

std::string WinUser::toString() const
{
    return toJson().toStyledString();
}

Json::Value WinUser::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserIcon())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserIcon();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserName())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getUserEmail())
            {
                ret[pMasqueradingVector[3]]=getValueOfUserEmail();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getUserPassword())
            {
                ret[pMasqueradingVector[4]]=getValueOfUserPassword();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUserEntryDate())
            {
                ret[pMasqueradingVector[5]]=getUserEntryDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getUserIcon())
    {
        ret["user_icon"]=getValueOfUserIcon();
    }
    else
    {
        ret["user_icon"]=Json::Value();
    }
    if(getUserName())
    {
        ret["user_name"]=getValueOfUserName();
    }
    else
    {
        ret["user_name"]=Json::Value();
    }
    if(getUserEmail())
    {
        ret["user_email"]=getValueOfUserEmail();
    }
    else
    {
        ret["user_email"]=Json::Value();
    }
    if(getUserPassword())
    {
        ret["user_password"]=getValueOfUserPassword();
    }
    else
    {
        ret["user_password"]=Json::Value();
    }
    if(getUserEntryDate())
    {
        ret["user_entry_date"]=getUserEntryDate()->toDbStringLocal();
    }
    else
    {
        ret["user_entry_date"]=Json::Value();
    }
    return ret;
}

bool WinUser::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("user_icon"))
    {
        if(!validJsonOfField(1, "user_icon", pJson["user_icon"], err, true))
            return false;
    }
    if(pJson.isMember("user_name"))
    {
        if(!validJsonOfField(2, "user_name", pJson["user_name"], err, true))
            return false;
    }
    else
    {
        err="The user_name column cannot be null";
        return false;
    }
    if(pJson.isMember("user_email"))
    {
        if(!validJsonOfField(3, "user_email", pJson["user_email"], err, true))
            return false;
    }
    else
    {
        err="The user_email column cannot be null";
        return false;
    }
    if(pJson.isMember("user_password"))
    {
        if(!validJsonOfField(4, "user_password", pJson["user_password"], err, true))
            return false;
    }
    else
    {
        err="The user_password column cannot be null";
        return false;
    }
    if(pJson.isMember("user_entry_date"))
    {
        if(!validJsonOfField(5, "user_entry_date", pJson["user_entry_date"], err, true))
            return false;
    }
    return true;
}
bool WinUser::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WinUser::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_icon"))
    {
        if(!validJsonOfField(1, "user_icon", pJson["user_icon"], err, false))
            return false;
    }
    if(pJson.isMember("user_name"))
    {
        if(!validJsonOfField(2, "user_name", pJson["user_name"], err, false))
            return false;
    }
    if(pJson.isMember("user_email"))
    {
        if(!validJsonOfField(3, "user_email", pJson["user_email"], err, false))
            return false;
    }
    if(pJson.isMember("user_password"))
    {
        if(!validJsonOfField(4, "user_password", pJson["user_password"], err, false))
            return false;
    }
    if(pJson.isMember("user_entry_date"))
    {
        if(!validJsonOfField(5, "user_entry_date", pJson["user_entry_date"], err, false))
            return false;
    }
    return true;
}
bool WinUser::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WinUser::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
